// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dota_commonmessages.proto

package com.valve.dota2;

public final class DotaCommonmessages {
  private DotaCommonmessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CDOTAMsg_LocationPingOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 x = 1;
    /**
     * <code>optional int32 x = 1;</code>
     */
    boolean hasX();
    /**
     * <code>optional int32 x = 1;</code>
     */
    int getX();

    // optional int32 y = 2;
    /**
     * <code>optional int32 y = 2;</code>
     */
    boolean hasY();
    /**
     * <code>optional int32 y = 2;</code>
     */
    int getY();

    // optional int32 target = 3;
    /**
     * <code>optional int32 target = 3;</code>
     */
    boolean hasTarget();
    /**
     * <code>optional int32 target = 3;</code>
     */
    int getTarget();

    // optional bool direct_ping = 4;
    /**
     * <code>optional bool direct_ping = 4;</code>
     */
    boolean hasDirectPing();
    /**
     * <code>optional bool direct_ping = 4;</code>
     */
    boolean getDirectPing();
  }
  /**
   * Protobuf type {@code com.valve.dota2.CDOTAMsg_LocationPing}
   */
  public static final class CDOTAMsg_LocationPing extends
      com.google.protobuf.GeneratedMessage
      implements CDOTAMsg_LocationPingOrBuilder {
    // Use CDOTAMsg_LocationPing.newBuilder() to construct.
    private CDOTAMsg_LocationPing(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CDOTAMsg_LocationPing(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CDOTAMsg_LocationPing defaultInstance;
    public static CDOTAMsg_LocationPing getDefaultInstance() {
      return defaultInstance;
    }

    public CDOTAMsg_LocationPing getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CDOTAMsg_LocationPing(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              x_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              y_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              target_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              directPing_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.valve.dota2.DotaCommonmessages.internal_static_com_valve_dota2_CDOTAMsg_LocationPing_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.valve.dota2.DotaCommonmessages.internal_static_com_valve_dota2_CDOTAMsg_LocationPing_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing.class, com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing.Builder.class);
    }

    public static com.google.protobuf.Parser<CDOTAMsg_LocationPing> PARSER =
        new com.google.protobuf.AbstractParser<CDOTAMsg_LocationPing>() {
      public CDOTAMsg_LocationPing parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CDOTAMsg_LocationPing(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CDOTAMsg_LocationPing> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 x = 1;
    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>optional int32 x = 1;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 x = 1;</code>
     */
    public int getX() {
      return x_;
    }

    // optional int32 y = 2;
    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>optional int32 y = 2;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 y = 2;</code>
     */
    public int getY() {
      return y_;
    }

    // optional int32 target = 3;
    public static final int TARGET_FIELD_NUMBER = 3;
    private int target_;
    /**
     * <code>optional int32 target = 3;</code>
     */
    public boolean hasTarget() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 target = 3;</code>
     */
    public int getTarget() {
      return target_;
    }

    // optional bool direct_ping = 4;
    public static final int DIRECT_PING_FIELD_NUMBER = 4;
    private boolean directPing_;
    /**
     * <code>optional bool direct_ping = 4;</code>
     */
    public boolean hasDirectPing() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool direct_ping = 4;</code>
     */
    public boolean getDirectPing() {
      return directPing_;
    }

    private void initFields() {
      x_ = 0;
      y_ = 0;
      target_ = 0;
      directPing_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, target_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, directPing_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, target_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, directPing_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.valve.dota2.CDOTAMsg_LocationPing}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.valve.dota2.DotaCommonmessages.internal_static_com_valve_dota2_CDOTAMsg_LocationPing_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.valve.dota2.DotaCommonmessages.internal_static_com_valve_dota2_CDOTAMsg_LocationPing_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing.class, com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing.Builder.class);
      }

      // Construct using com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        target_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        directPing_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.valve.dota2.DotaCommonmessages.internal_static_com_valve_dota2_CDOTAMsg_LocationPing_descriptor;
      }

      public com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing getDefaultInstanceForType() {
        return com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing.getDefaultInstance();
      }

      public com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing build() {
        com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing buildPartial() {
        com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing result = new com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.target_ = target_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.directPing_ = directPing_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing) {
          return mergeFrom((com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing other) {
        if (other == com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasTarget()) {
          setTarget(other.getTarget());
        }
        if (other.hasDirectPing()) {
          setDirectPing(other.getDirectPing());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.valve.dota2.DotaCommonmessages.CDOTAMsg_LocationPing) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 x = 1;
      private int x_ ;
      /**
       * <code>optional int32 x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 x = 1;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>optional int32 x = 1;</code>
       */
      public Builder setX(int value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 x = 1;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        onChanged();
        return this;
      }

      // optional int32 y = 2;
      private int y_ ;
      /**
       * <code>optional int32 y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 y = 2;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>optional int32 y = 2;</code>
       */
      public Builder setY(int value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 y = 2;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0;
        onChanged();
        return this;
      }

      // optional int32 target = 3;
      private int target_ ;
      /**
       * <code>optional int32 target = 3;</code>
       */
      public boolean hasTarget() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 target = 3;</code>
       */
      public int getTarget() {
        return target_;
      }
      /**
       * <code>optional int32 target = 3;</code>
       */
      public Builder setTarget(int value) {
        bitField0_ |= 0x00000004;
        target_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 target = 3;</code>
       */
      public Builder clearTarget() {
        bitField0_ = (bitField0_ & ~0x00000004);
        target_ = 0;
        onChanged();
        return this;
      }

      // optional bool direct_ping = 4;
      private boolean directPing_ ;
      /**
       * <code>optional bool direct_ping = 4;</code>
       */
      public boolean hasDirectPing() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool direct_ping = 4;</code>
       */
      public boolean getDirectPing() {
        return directPing_;
      }
      /**
       * <code>optional bool direct_ping = 4;</code>
       */
      public Builder setDirectPing(boolean value) {
        bitField0_ |= 0x00000008;
        directPing_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool direct_ping = 4;</code>
       */
      public Builder clearDirectPing() {
        bitField0_ = (bitField0_ & ~0x00000008);
        directPing_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.valve.dota2.CDOTAMsg_LocationPing)
    }

    static {
      defaultInstance = new CDOTAMsg_LocationPing(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.valve.dota2.CDOTAMsg_LocationPing)
  }

  public interface CDOTAMsg_MapLineOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 x = 1;
    /**
     * <code>optional int32 x = 1;</code>
     */
    boolean hasX();
    /**
     * <code>optional int32 x = 1;</code>
     */
    int getX();

    // optional int32 y = 2;
    /**
     * <code>optional int32 y = 2;</code>
     */
    boolean hasY();
    /**
     * <code>optional int32 y = 2;</code>
     */
    int getY();

    // optional bool initial = 3;
    /**
     * <code>optional bool initial = 3;</code>
     */
    boolean hasInitial();
    /**
     * <code>optional bool initial = 3;</code>
     */
    boolean getInitial();
  }
  /**
   * Protobuf type {@code com.valve.dota2.CDOTAMsg_MapLine}
   */
  public static final class CDOTAMsg_MapLine extends
      com.google.protobuf.GeneratedMessage
      implements CDOTAMsg_MapLineOrBuilder {
    // Use CDOTAMsg_MapLine.newBuilder() to construct.
    private CDOTAMsg_MapLine(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CDOTAMsg_MapLine(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CDOTAMsg_MapLine defaultInstance;
    public static CDOTAMsg_MapLine getDefaultInstance() {
      return defaultInstance;
    }

    public CDOTAMsg_MapLine getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CDOTAMsg_MapLine(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              x_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              y_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              initial_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.valve.dota2.DotaCommonmessages.internal_static_com_valve_dota2_CDOTAMsg_MapLine_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.valve.dota2.DotaCommonmessages.internal_static_com_valve_dota2_CDOTAMsg_MapLine_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine.class, com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine.Builder.class);
    }

    public static com.google.protobuf.Parser<CDOTAMsg_MapLine> PARSER =
        new com.google.protobuf.AbstractParser<CDOTAMsg_MapLine>() {
      public CDOTAMsg_MapLine parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CDOTAMsg_MapLine(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CDOTAMsg_MapLine> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 x = 1;
    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>optional int32 x = 1;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 x = 1;</code>
     */
    public int getX() {
      return x_;
    }

    // optional int32 y = 2;
    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>optional int32 y = 2;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 y = 2;</code>
     */
    public int getY() {
      return y_;
    }

    // optional bool initial = 3;
    public static final int INITIAL_FIELD_NUMBER = 3;
    private boolean initial_;
    /**
     * <code>optional bool initial = 3;</code>
     */
    public boolean hasInitial() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool initial = 3;</code>
     */
    public boolean getInitial() {
      return initial_;
    }

    private void initFields() {
      x_ = 0;
      y_ = 0;
      initial_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, initial_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, initial_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.valve.dota2.CDOTAMsg_MapLine}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLineOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.valve.dota2.DotaCommonmessages.internal_static_com_valve_dota2_CDOTAMsg_MapLine_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.valve.dota2.DotaCommonmessages.internal_static_com_valve_dota2_CDOTAMsg_MapLine_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine.class, com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine.Builder.class);
      }

      // Construct using com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        initial_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.valve.dota2.DotaCommonmessages.internal_static_com_valve_dota2_CDOTAMsg_MapLine_descriptor;
      }

      public com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine getDefaultInstanceForType() {
        return com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine.getDefaultInstance();
      }

      public com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine build() {
        com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine buildPartial() {
        com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine result = new com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.initial_ = initial_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine) {
          return mergeFrom((com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine other) {
        if (other == com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasInitial()) {
          setInitial(other.getInitial());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.valve.dota2.DotaCommonmessages.CDOTAMsg_MapLine) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 x = 1;
      private int x_ ;
      /**
       * <code>optional int32 x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 x = 1;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>optional int32 x = 1;</code>
       */
      public Builder setX(int value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 x = 1;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        onChanged();
        return this;
      }

      // optional int32 y = 2;
      private int y_ ;
      /**
       * <code>optional int32 y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 y = 2;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>optional int32 y = 2;</code>
       */
      public Builder setY(int value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 y = 2;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0;
        onChanged();
        return this;
      }

      // optional bool initial = 3;
      private boolean initial_ ;
      /**
       * <code>optional bool initial = 3;</code>
       */
      public boolean hasInitial() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool initial = 3;</code>
       */
      public boolean getInitial() {
        return initial_;
      }
      /**
       * <code>optional bool initial = 3;</code>
       */
      public Builder setInitial(boolean value) {
        bitField0_ |= 0x00000004;
        initial_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool initial = 3;</code>
       */
      public Builder clearInitial() {
        bitField0_ = (bitField0_ & ~0x00000004);
        initial_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.valve.dota2.CDOTAMsg_MapLine)
    }

    static {
      defaultInstance = new CDOTAMsg_MapLine(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.valve.dota2.CDOTAMsg_MapLine)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_valve_dota2_CDOTAMsg_LocationPing_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_valve_dota2_CDOTAMsg_LocationPing_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_valve_dota2_CDOTAMsg_MapLine_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_valve_dota2_CDOTAMsg_MapLine_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031dota_commonmessages.proto\022\017com.valve.d" +
      "ota2\032 google/protobuf/descriptor.proto\032\021" +
      "netmessages.proto\"R\n\025CDOTAMsg_LocationPi" +
      "ng\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002 \001(\005\022\016\n\006target\030\003 \001(\005" +
      "\022\023\n\013direct_ping\030\004 \001(\010\"9\n\020CDOTAMsg_MapLin" +
      "e\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002 \001(\005\022\017\n\007initial\030\003 \001(\010" +
      "B\005H\001\200\001\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_valve_dota2_CDOTAMsg_LocationPing_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_valve_dota2_CDOTAMsg_LocationPing_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_valve_dota2_CDOTAMsg_LocationPing_descriptor,
              new java.lang.String[] { "X", "Y", "Target", "DirectPing", });
          internal_static_com_valve_dota2_CDOTAMsg_MapLine_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_valve_dota2_CDOTAMsg_MapLine_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_valve_dota2_CDOTAMsg_MapLine_descriptor,
              new java.lang.String[] { "X", "Y", "Initial", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
          com.valve.dota2.Netmessages.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
